name = "infinibuild-api-dev"
route = "dev.api.infini.build"

main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "0.0.10"
ENVIRONMENT = "dev"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.production]
name = "infinibuild-api"
route = "api.infini.build"
vars = { WORKERS_RS_VERSION = "0.0.10", ENVIRONMENT = "production" }