name: ci-dev.yml

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    name: Test Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cargo
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Build
        run: cargo build --verbose
        
      - name: Run tests
        run: cargo test --verbose

  deploy:
    name: Deploy to Cloudflare Workers
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish
        uses: CodeCrowCorp/wrangler-rs-action@0.0.1
        with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            command: publish
