name: ci-prod.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:

  test:
    name: Test Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cargo
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Build
        run: cargo build --verbose
        
      - name: Run tests
        run: cargo test --verbose

  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Publish
        uses: CodeCrowCorp/wrangler-rs-action@0.0.1
        with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            command: publish --env production

  create-tag:
    name: Create Tag and Release
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get NPM version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        
      - name: Create a tag and release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ steps.package-version.outputs.current-version }}
          name: v${{ steps.package-version.outputs.current-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
        continue-on-error: true