name: deploy-and-release.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env ${{ secrets.ENVIRONMENT }}
        env:
          WORKERS_RS_VERSION: ${{ secrets.WORKERS_RS_VERSION }}

  create-tag:
    name: Create Tag
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get NPM version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/release/${{ steps.package-version.outputs.current-version}}',
              sha: context.sha
            })

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [create-tag]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

